services:
  app:
    profiles: ["main"]
    build: .
    working_dir: /app
    volumes:
      - .:/app
    # command: uv run python src/main.py
    # command sleep
    # command: tail -F anything
  notebook:
    profiles: ["notebook"]
    build: .
    working_dir: /app
    volumes:
      - .:/app
